src/App.Web/Models/ViewModels/App/WBSTreeViewModel.cs
using App.Domain.DTO.App;
using App.Domain.Models.App;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace App.Web.Models.ViewModels.App
{
    public class WBSTreeViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid IdWBS { get; set; }
        public Guid? ParentId { get; set; }
        public string Lokasi { get; set; }
        public string NamaLokasi { get; set; }
        public string GrupHarga { get; set; }
        public string Type { get; set; }
        public string Regional { get; set; }
        public string Witel { get; set; }
        public string Datel { get; set; }
    }

    public class WBSTreeForm
    {
        [Required]
        public string Name { get; set; }
        public Guid IdWBS { get; set; }
        public Guid? ParentId { get; set; }
        public string Lokasi { get; set; }
        [UIHint("Autocomplete")]
        public string NamaLokasi { get; set; }
        public string GrupHarga { get; set; }
        public string Type { get; set; }
        public string Regional { get; set; }
        public string Witel { get; set; }
        public string Datel { get; set; }
        public bool HasKHS { get; set; }
    }

    public class WBSBoQViewModel
    {
        public WBS WBS { get; set; }
        public WBSTree Lokasi { get; set; }
        public List<WBSBoQDto> Paket { get; set; }
        [UIHint("TreeCategory")]
        public string WBSCategory { get; set; }
        [Required]
        [UIHint("SingleFileUploadBoQ")]
        public string FileBoQ { get; set; }
    }
}

src/App.Web/Areas/Admin/Controllers/Api/App/WBSTreesController.cs
using App.Domain.DTO.App;
using App.Domain.Models.App;
using App.Domain.Models.Identity;
using App.Helper;
using App.Infrastructure;
using App.Services.App;
using App.Services.Identity;
using App.Web.Models.ViewModels.App;
using App.Web.Models.ViewModels.Lemon;
using AutoMapper;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pomelo.Data.MySql;
using System;
using System.Collections.Generic;
using System.Linq;
using App.Web.Helper;
namespace App.Web.Areas.Admin.Controllers.Api.App
{
    [Produces("application/json")]
    [Route("admin/api/wbstrees")]
    public class WBSTreesController : BaseApiController<WBSTree, IWBSTreeService, WBSTreeDto, Guid>
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitService _unitService;
        private readonly IWBSService _wbsService;
        private readonly IWBSBoQService _wbsBoqService;
        private readonly IDesignatorService _designatorService;
        private readonly ConfigHelper _configHelper;
        private readonly string _DefaultEmailEndPoint;
        public WBSTreesController(
            IHttpContextAccessor httpContextAccessor,
            IUserService userService,
            IMapper mapper, IWBSTreeService service,
            IWBSService wbsService,
            IUnitService unitService,
            IDesignatorService designatorService,
            IWBSBoQService wbsBoqService,
             ConfigHelper configHelper,
        UserManager<ApplicationUser> userManager,
            IUserHelper userHelper) : base(httpContextAccessor, userService, mapper, service, userHelper)
        {
            _wbsService = wbsService;
            _unitService = unitService;
            _userManager = userManager;
            _designatorService = designatorService;
            _wbsBoqService = wbsBoqService;
            _configHelper = configHelper;
            _DefaultEmailEndPoint = _configHelper.GetConfig("transformer.rest.api.url");

        }

        [HttpPost]
        [Route("createwbs")]
        public IActionResult PostDatawbstree(WBSTreeForm model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            WBSTree item = Mapper.Map<WBSTree>(model);

            if (model.ParentId != null)
            {
                item.ParentId = model.ParentId;
            }
            item.Type = WBS.WBS_TYPE_WBS;

            Service.Add(item);

            return Ok(item);
        }
        [HttpGet]
        [Route("getkelomokharga/{id}")]
        public IActionResult getKelomokHarga(Guid Id)
        {
            var datatree = Service.GetById(Id);
            if (datatree == null)
            {
                return NotFound();
            }
            var grup = datatree.GrupHarga;
            return Ok(grup);
        }

        [HttpGet]
        [Route("getwbstrees/{id}")]
        public IActionResult getWbstree(Guid Id)
        {
            var datatree = Service.GetPerentDataWbs(Id);
            return Ok(datatree);
        }

        [HttpGet]
        [Route("getchildwbstrees/{id}")]
        public IActionResult getWbsChildtree(Guid Id)
        {
            var datatree = Service.GetchildDataWbs(Id);
            return Ok(datatree);
        }

        [HttpGet]
        [Route("getwbschild/{id}")]
        public IActionResult getWbsalltree(Guid Id, Guid? Idperent)
        {

            if (Id == null)
            {
                return BadRequest();
            }
            var model = new WBSUnit();
            if (CurrentUser.Id == null)
            {
                return BadRequest();
            }
            var claims = _userManager.GetClaimsAsync(CurrentUser).Result;

            var unitId = claims
                          .FirstOrDefault(x => x.Type == ApplicationUser.UNIT_CLAIMS)?.Value;

            if (unitId == null)
            {
                return BadRequest();
            }
            var unitBagian = _unitService.GetById(unitId);

            if (unitBagian != null && unitBagian.STLevel == Unit.STLevelBagian)
                unitId = unitBagian.ParentId;
            else
                unitBagian = null;

            var unitKerja = _unitService.GetById(unitId);
            var unitBisnis = _unitService.GetById(unitKerja.ParentId);
            var wbs = _wbsService.GetById(Id);
            if (unitBisnis == null)
            {
                return BadRequest();
            }
            model.UnitBisnis = unitBisnis.NamaUnit;
            if (unitKerja == null)
            {
                return BadRequest();
            }
            model.UnitKerja = unitKerja.NamaUnit;
            model.KodeUnit = unitKerja.Id;
            if (wbs == null)
            {
                return BadRequest();
            }

            if (Idperent == null && Idperent == null)
            {

                string data = "[{\"icon\":\"fa fa-folder icon-state-warning icon-lg\",\n";
                data += $"\"id\":\"{wbs.Id}\",\n";
                data += $"\"text\":\"{wbs.NamaKegiatan}\",\n";
                data += "\"type\":\"root\",\n";
                data += "\"ParentId\":null,\n";
                data += "\"children\":true}]";

                var dynamic = JsonConvert.DeserializeObject<dynamic>(data);
                return Ok(dynamic);
            }
            var idunitbissnis = new Guid("00000000-0000-0000-0000-000000000001");
            if (Id == Idperent)
            {
                string data = "[{\"icon\":\"fa fa-folder icon-state-warning icon-lg\",\n";
                data += $"\"id\":\"{idunitbissnis}\",\n";
                data += $"\"text\":\"{unitBisnis.NamaUnit}\",\n";
                data += $"\"ParentId\":\"{Idperent}\",\n";
                data += "\"children\":true}]";
                var dynamic = JsonConvert.DeserializeObject<dynamic>(data);
                return Ok(dynamic);
            }
            var idunitkerja = new Guid("00000000-0000-0000-0000-000000000003");
            if (idunitbissnis == Idperent)
            {
                var boolechild = Service.GetAll().Where(c => c.ParentId.Equals(null) && c.IdWBS.Equals(Id)).Count() == 0 ? "\"children\":false" : "\"children\":true"; ;
                string data = "[{\"icon\":\"fa fa-folder icon-state-warning icon-lg\",\n";
                data += $"\"id\":\"{idunitkerja}\",\n";
                data += $"\"text\":\"{unitKerja.NamaUnit}\",\n";
                data += $"\"ParentId\":\"{idunitbissnis}\",\n";
                data += boolechild;
                data += "}]";
                var dynamic = JsonConvert.DeserializeObject<dynamic>(data);
                return Ok(dynamic);
            }
            if (idunitkerja == Idperent)
            {
                var x = from servicewbstree in Service.GetAll()
                        where servicewbstree.IdWBS.Equals(Id) && servicewbstree.ParentId.Equals(null)
                        select new
                        {
                            children = Service.GetAll().Where(c => c.ParentId.Equals(servicewbstree.Id)).Count() == 0 ? false : true,
                            icon = "fa fa-folder icon-state-warning icon-lg",
                            id = servicewbstree.Id.ToString(),
                            text = servicewbstree.Name,
                            ParentId = Idperent,
                        };
                return Ok(x.ToArray().OrderBy(c => c.id));
            }
            else
            {
                var x = from servicewbstree in Service.GetAll()
                        where servicewbstree.ParentId.Equals(Idperent) && servicewbstree.IdWBS.Equals(Id)
                        select new
                        {
                            children = Service.GetAll().Where(c => c.ParentId.Equals(servicewbstree.Id)).Count() == 0 ? false : true,
                            icon = Service.GetAll().Where(c => c.ParentId.Equals(servicewbstree.Id)).Count() == 0 ? "fa fa-file icon-state-success" : "fa fa-folder icon-state-warning icon-lg",
                            id = servicewbstree.Id.ToString(),
                            text = servicewbstree.Name,
                            ParentId = Idperent,
                        };
                return Ok(x.ToArray().OrderBy(c => c.id));
            }


        }
        [HttpGet]
        [Route("GetWbstree")]
        public IActionResult GetTree(Guid IdWbs)
        {
            var data = Service.GetLeveledName(IdWbs);
            var select2 = from dataselect in data
                          select new
                          {
                              text = dataselect.Value,
                              id = dataselect.Key
                          };

            return Ok(select2.ToList());
        }

        [HttpGet]
        [Route("GetLocationtree")]
        public IActionResult GetLocation(Guid ParentId)
        {
            var data = Service.GetLocation(ParentId);
            return Ok(data);
        }

        [HttpPost]
        [Route("datatablesjoin")]
        public IActionResult Datatablesjoin(Guid id, IDataTablesRequest request)
        {
            var listguid = new List<Guid>();

            var ListGuid = Service.getListguid(id, listguid);

            if (ListGuid.Count() == 0)
            {
                var IdWBStree = Service.GetById(id);

                if (IdWBStree != null && IdWBStree.Type == WBS.WBS_TYPE_LOCATION)
                {
                    listguid.Add(IdWBStree.Id);
                }               
            }

            var dataBoq = _wbsBoqService.getdtafromlist(ListGuid);
         
            var data = from BoqCustom in dataBoq
                       join designator in _designatorService.GetAll()
                       on BoqCustom.IdDesignator equals designator.IdDesignator

src/App.Web/Areas/Admin/Controllers/App/WBSTreeController.cs
using App.Domain.Models.App;
using App.Helper;
using App.Infrastructure;
using App.Services.App;
using App.Services.Identity;
using App.Web.Models.ViewModels.App;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace App.Web.Areas.Admin.Controllers.App
{
    [Area("Admin")]
    public class WBSTreeController : BaseController<WBSTree, IWBSTreeService, WBSTreeViewModel, WBSTreeForm, Guid>
    {
        public WBSTreeController(IHttpContextAccessor httpContextAccessor,
            IUserService userService,
            IMapper mapper,
            IWBSTreeService service,
            IUserHelper userHelper)
            : base(httpContextAccessor, userService, mapper, service, userHelper)
        {
        }

        public IActionResult CreateWBS(Guid idWbs, Guid? parent)
        {
            var model = new WBSTreeForm
            {
                IdWBS = idWbs,
                ParentId = parent,
                Type = WBS.WBS_TYPE_WBS
            };

            return View("Create", model);
        }

        public IActionResult CreateLokasi(Guid idWbs, Guid? parent)
        {
            var model = new WBSTreeForm
            {
                IdWBS = idWbs,
                ParentId = parent,
                Type = WBS.WBS_TYPE_LOCATION
            };

            return View("CreateLokasi", model);
        }

        [HttpPost]
        public override IActionResult Create(WBSTreeForm model)
        {
            if (ModelState.IsValid)
            {
                var item = Mapper.Map<WBSTree>(model);

                if (item.ParentId.HasValue)
                {
                    if (item.Type == WBS.WBS_TYPE_LOCATION)
                    {
                        UpdateParent(item.ParentId.Value, WBS.WBS_TYPE_WP);
                    }
                    else if (item.Type == WBS.WBS_TYPE_WBS)
                    {
                        UpdateParent(item.ParentId.Value, WBS.WBS_TYPE_WBS_HAS_WBS);
                    }
                }

                item.CreatedAt = DateTime.Now;
                item.CreatedBy = CurrentUser.Id;

                Service.Add(item);

                return Ok(model);
            }

            return BadRequest(model);
        }

        public IActionResult EditWBS(Guid id)
        {
            var wbs = Service.GetById(id);

            if (wbs == null)
                return NotFound();

            ViewBag.Id = id;

            var model = Mapper.Map<WBSTreeForm>(wbs);

            return View("Edit", model);
        }

        public IActionResult EditLokasi(Guid id)
        {
            var lokasi = Service.GetById(id);

            if (lokasi == null)
                return NotFound();

            ViewBag.Id = id;

            var model = Mapper.Map<WBSTreeForm>(lokasi);

            model.Regional = lokasi.AreaMapping?.AreaRegional;
            model.Witel = lokasi.AreaMapping?.AreaWitel;
            model.Datel = lokasi.AreaMapping?.AreaDatel;
            model.NamaLokasi = $"{lokasi.AreaMapping?.AreaStoName} ({lokasi.AreaMapping?.AreaSto})";

            if (lokasi.GrupHarga != null)
            {
                model.HasKHS = true;
            }

            return View("EditLokasi", model);
        }

        [HttpPost]
        public override IActionResult Edit(Guid id, WBSTreeForm model)
        {
            if (ModelState.IsValid)
            {
                var item = Service.GetById(id);

                if (item == null)
                {
                    return NotFound();
                }

                item.Name = model.Name;
                item.Lokasi = model.Lokasi;
                item.GrupHarga = model.GrupHarga;
                item.LastUpdateTime = DateTime.Now;
                item.LastEditedBy = CurrentUser.Id;

                var result = Service.Update(item);

                return Ok(model);
            }

            return BadRequest(model);
        }

        private void UpdateParent(Guid parentId, string type)
        {
            var item = Service.GetById(parentId);
            item.Type = type;
            Service.Update(item);
            if (item.ParentId.HasValue)
            {
                if (item.Type == WBS.WBS_TYPE_WP)
                {
                    type = WBS.WBS_TYPE_WBS_HAS_LOCATION;
                }

                UpdateParent(item.ParentId.Value, type);
            }
        }
    }
}

src/App.Web/Areas/Admin/Views/WBSTree/Create.cshtml
@model WBSTreeForm

@{
    Layout = null;
}


<form id="WBSTreeCreate" role="form" asp-action="Create" method="post" asp-controller="WBSTree">
    <div class="role-body">
        <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button> @Localization.GetLocalized("common.validation.text.error")
        </div>
        <div class="alert alert-success display-hide">
            <button class="close" data-close="alert"></button> @Localization.GetLocalized("common.validation.text.success")
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger" id="validation-summary"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label">
                @Localization.GetLocalized("wbstree.text.create.name")
                <span class="text-danger"> * </span>
            </label>
            <div>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger" />
                <input asp-for="ParentId" class="form-control" type="hidden" />
                <input asp-for="IdWBS" class="form-control" type="hidden" />
                <input asp-for="Type" class="form-control" type="hidden" />
            </div>
        </div>
        <hr />
        <div class="form-actions pull-right">
            <input type="submit" value="@Localization.GetLocalized("common.button.save")" class="btn blue" />
            <button type="button" class="btn default bootbox-close-button">@Localization.GetLocalized("common.button.cancel")</button>
        </div>
        <div class="clearfix"></div>
    </div>
</form>

src/App.Web/Areas/Admin/Views/WBSTree/CreateLokasi.cshtml
@model WBSTreeForm

@{
    Layout = null;
}


<form id="WBSTreeCreate" role="form" asp-action="Create" method="post" asp-controller="WBSTree">
    <div class="role-body">
        <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button> @Localization.GetLocalized("common.validation.text.error")
        </div>
        <div class="alert alert-success display-hide">
            <button class="close" data-close="alert"></button> @Localization.GetLocalized("common.validation.text.success")
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger" id="validation-summary"></div>
        <div class="form-group">
            <label asp-for="Lokasi" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.areastoname")
                <span class="text-danger"> * </span>
            </label>
            <div>
                @Html.EditorFor(model => model.NamaLokasi, new { url = "/admin/api/stos/autocomplete", displayKey = "areaKode" })
            </div>
        </div>
        <div class="form-group">
            <label asp-for="HasKHS" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.has.khs")
                <span class="text-danger"> * </span>
            </label>
            <div>
                <div class="mt-checkbox-list" data-error-container="#roles_error">
                    <label class="mt-checkbox">
                        <input asp-for="HasKHS" />
                        <span></span>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group hidden" id="Harga">
            <label asp-for="GrupHarga" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.grupharga")
                <span class="text-danger"> * </span>
            </label>
            <div>
                <select asp-for="GrupHarga" class="form-control">
                    <option value="@Model.GrupHarga" selected>@Model.GrupHarga</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.name")
                <span class="text-danger"> * </span>
            </label>
            <div>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger" />
                <input asp-for="ParentId" class="form-control" type="hidden" />
                <input asp-for="IdWBS" class="form-control" type="hidden" />
                <input asp-for="Type" class="form-control" type="hidden" />
                <input asp-for="Lokasi" class="form-control" type="hidden" />
            </div>
        </div>
        <hr />
        <div class="form-actions pull-right">
            <input type="submit" value="@Localization.GetLocalized("common.button.save")" class="btn blue" />
            <button type="button" class="btn default bootbox-close-button">@Localization.GetLocalized("common.button.cancel")</button>
        </div>
        <div class="clearfix"></div>
    </div>
</form>

<script>
    $(document).ready(function () {

        $("#HasKHS").change(function () {
            if (this.checked) {
                $("#Harga").removeClass("hidden");
            } else {
                $("#Harga").addClass("hidden");
            }
           
        });

        $("#GrupHarga").select2({
            width: "100%",
            ajax: {
                url: '/admin/api/designators/grup',
                dataType: 'json',
                type: "GET",
                quietMillis: 500,
                data: function (term) {
                    return {
                        query: term.term
                    };
                },
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item,
                                id: item
                            }
                        })
                    };
                }
            }
        });
    });
</script>

src/App.Web/Areas/Admin/Views/WBSTree/Edit.cshtml
@model WBSTreeForm

@{
    Layout = null;
}


<form id="WBSTreeEdit" role="form" asp-route-id="@ViewBag.Id" asp-action="Edit" method="post" asp-controller="WBSTree">
    <div class="role-body">
        <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button> @Localization.GetLocalized("common.validation.text.error")
        </div>
        <div class="alert alert-success display-hide">
            <button class="close" data-close="alert"></button> @Localization.GetLocalized("common.validation.text.success")
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger" id="validation-summary"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.name")
                <span class="text-danger"> * </span>
            </label>
            <div>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger" />
                <input asp-for="ParentId" class="form-control" type="hidden" />
                <input asp-for="IdWBS" class="form-control" type="hidden" />
                <input asp-for="Type" class="form-control" type="hidden" />
            </div>
        </div>
        <hr />
        <div class="form-actions pull-right">
            <input type="submit" value="@Localization.GetLocalized("common.button.save")" class="btn blue" />
            <button type="button" class="btn default bootbox-close-button">@Localization.GetLocalized("common.button.cancel")</button>
        </div>
        <div class="clearfix"></div>
    </div>
</form>

src/App.Web/Areas/Admin/Views/WBSTree/EditLokasi.cshtml
@model WBSTreeForm

@{
    Layout = null;
}


<form id="WBSTreeEdit" role="form" asp-action="Edit" asp-route-id="@ViewBag.Id" method="post" asp-controller="WBSTree">
    <div class="role-body">
        <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button> @Localization.GetLocalized("common.validation.text.error")
        </div>
        <div class="alert alert-success display-hide">
            <button class="close" data-close="alert"></button> @Localization.GetLocalized("common.validation.text.success")
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger" id="validation-summary"></div>
        <div class="form-group">
            <label asp-for="Lokasi" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.areastoname")
                <span class="text-danger"> * </span>
            </label>
            <div>
                @Html.EditorFor(model => model.NamaLokasi, new { url = "/admin/api/stos/autocomplete", displayKey = "areaKode", value = Model.Lokasi })
            </div>
        </div>
        <div class="form-group">
            <label asp-for="HasKHS" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.has.khs")
                <span class="text-danger"> * </span>
            </label>
            <div>
                <div class="mt-checkbox-list" data-error-container="#roles_error">
                    <label class="mt-checkbox">
                        <input asp-for="HasKHS" />
                        <span></span>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group hidden" id="Harga">
            <label asp-for="GrupHarga" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.grupharga")
                <span class="text-danger"> * </span>
            </label>
            <div>
                <select asp-for="GrupHarga" class="form-control">
                    <option value="@Model.GrupHarga" selected>@Model.GrupHarga</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="control-label">
                @Localization.GetLocalized("resource.text.create.wbs.name")
                <span class="text-danger"> * </span>
            </label>
            <div>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger" />
                <input asp-for="ParentId" class="form-control" type="hidden" />
                <input asp-for="IdWBS" class="form-control" type="hidden" />
                <input asp-for="Type" class="form-control" type="hidden" />
                <input asp-for="Lokasi" class="form-control" type="hidden" />
            </div>
        </div>
        <hr />
        <div class="form-actions pull-right">
            <input type="submit" value="@Localization.GetLocalized("common.button.save")" class="btn blue" />
            <button type="button" class="btn default bootbox-close-button">@Localization.GetLocalized("common.button.cancel")</button>
        </div>
        <div class="clearfix"></div>
    </div>
</form>

<script>
    $(document).ready(function () {

        if ($('input#HasKHS').is(':checked')) {
            $("#Harga").removeClass("hidden");
        }

        $("#HasKHS").change(function () {
            if (this.checked) {
                $("#Harga").removeClass("hidden");
            } else {
                $("#Harga").addClass("hidden");
                $("#GrupHarga").val("");
            }
        });

        $("#GrupHarga").select2({
            width: "100%",
            ajax: {
                url: '/admin/api/designators/grup',
                dataType: 'json',
                type: "GET",
                quietMillis: 500,
                data: function (term) {
                    return {
                        query: term.term
                    };
                },
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item,
                                id: item
                            }
                        })
                    };
                }
            }
        });
    });
</script>